const TRANSLATIONS_EN = {
    header_sub: "Driver Intelligence Hub",
    search_placeholder: "Search city, region or attraction...",
    menu_briefings_title: "City Access Guides",
    menu_briefings_desc: "Drop-offs, parking & instructions",
    menu_map_title: "Interactive Map",
    menu_map_desc: "Parking, Drop-offs, Service",
    menu_pitstop_title: "Pit Stop",
    menu_pitstop_desc: "Waste disposal & services",
    menu_handbook_title: "Handbook",
    menu_handbook_desc: "Regulations & Tacho",
    menu_emergency_title: "Emergency",
    menu_emergency_desc: "SOS & Breakdown",
    pitstop_alert: "Feature coming soon",
    back_to_menu: "← Menu",
    back: "← Back",
    browse_regions: "Select Region",
    
    // Filtry Mapy i Popup
    map_filter_all: "All",
    map_filter_parking: "Parking",
    map_filter_dropoff: "Drop-off",
    map_filter_service: "Service",
    map_view_briefing: "View Access Instructions",
    category_parking: "Coach Parking",
    category_dropoff: "Set-down / Pick-up Point",
    category_service: "Service & Facilities",
    
    // Emergency sekcja
    emergency_text: "Need assistance? Share your location with the service team.",
    sos_button: "📍 SHARE MY LOCATION",
    quick_call: "Quick Call:",

    regions: {
        "Central London": "Central London",
        "City of London": "City of London",
        "North West London": "North West London",
        "South East London": "South East London",
        "Greater London": "Greater London",
        "Cheshire": "Cheshire",
        "Cornwall": "Cornwall",
        "Dorset": "Dorset",
        "East Midlands": "East Midlands",
        "East of England": "East of England",
        "Greater Manchester": "Greater Manchester",
        "Highlands": "Highlands",
        "Isle of Wight": "Isle of Wight",
        "Lake District": "Lake District",
        "Midlands": "Midlands",
        "North East": "North East",
        "North Wales": "North Wales",
        "North West": "North West",
        "North Yorkshire": "North Yorkshire",
        "Oxfordshire": "Oxfordshire",
        "Scotland": "Scotland",
        "South": "South England",
        "South East": "South East England",
        "South West": "South West England",
        "West Midlands": "West Midlands",
        "West Yorkshire": "West Yorkshire",
        "Worcestershire": "Worcestershire",
        "Yorkshire": "Yorkshire & Humber"
    },
    categories: {
        "transit hub": "Transit Hub",
        "transport hub": "Transport Hub",
        "politics & heritage": "Politics & Heritage",
        "shopping": "Shopping",
        "tourism": "Tourism",
        "attraction": "Attraction",
        "city": "City",
        "ferry": "Ferry",
        "sports & events": "Sports & Events",
        "maritime heritage": "Maritime Heritage"
    },
    search_results: "Search Results",
    operational_briefing: "Driver Access Instructions",
    step1_label: "1. Set-down / Pick-up Point",
    step2_label: "2. Coach Parking",
    step3_label: "3. Facilities",
    default_step1_title: "Set-down & Pick-up",
    default_step2_title: "Coach Parking",
    default_step3_title: "Facilities & Info"
};