const TRANSLATIONS_PL = {
    header_sub: "Centrum Informacji Kierowcy",
    search_placeholder: "Szukaj miasta...",
    menu_briefings_title: "Wjazd do Miast",
    menu_briefings_desc: "Zatoczki, parkingi i instrukcje",
    menu_pitstop_title: "Pit Stop",
    menu_pitstop_desc: "Serwis i zrzut nieczystości",
    pitstop_alert: "Funkcja dostępna wkrótce",
    back_to_menu: "← Menu",
    back: "← Powrót",
    browse_regions: "Wybierz Region",
    regions: {
        "Greater London": "Londyn i okolice",
        "West Midlands": "West Midlands",
        "North West": "North West",
        "Yorkshire": "Yorkshire",
        "South West": "South West",
        "North East": "North East",
        "East Midlands": "East Midlands",
        "South": "South Coast"
    },
    search_results: "Wyniki wyszukiwania",
    operational_briefing: "Instrukcja Dojazdu i Postoju",
    step1_label: "1. Punkt Docelowy / Drop-off",
    step2_label: "2. Parking / Postój",
    step3_label: "3. Zaplecze (WC / Kawa)",
    default_step1_title: "Brak danych punktu",
    default_step1_desc: "Sprawdź oznakowanie lokalne.",
    no_results_for: "Nie znaleziono",
    loading_protocols: "Wczytywanie danych...",
    searching: "Szukam...",
    connection_failed: "Błąd połączenia z bazą"
};